# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b3ba45b43321d2ff5d69c77fce87cb82260140923bd582b00627535256907e1d7289fca56d15ed178ee2bd181884b166d3dd73127b43e85e397ab1099eb45c

test:
  secret_key_base: e22f413f0fe8eb67eae1a01592b27b0ded0619c66ee9090e7055814550b634014fc5e35361b534d7a1a3ea67d4c2738485faa01642f614cdcd8157c6a30b69ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
